
### Variables
@port = 3000


### Get todos

GET http://localhost:{{port}}/api/todos

### Create a todo

POST http://localhost:{{port}}/api/todos
Content-Type: application/json

{
  "item": "Take out the trash"
}

### Toggle completed status of a todo

PUT http://localhost:{{port}}/api/todos/662401209563c0d8261720cb
